ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\Admin\Downloads\New folder")
Sleep(2000)
ControlFocus("Open","","Button1")
ControlClick("Open","","Button1")
